language: php
os:
  - linux
dist: bionic

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
    - 7.4

install:
    - composer update

script:
    - vendor/phpunit/phpunit/phpunit --verbose
