sudo: false

dist: xenial

services: mysql

language: php

php:
    - 7.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - composer update

script:
    - vendor/phpunit/phpunit/phpunit --verbose
