language: php
os:
  - linux
dist: bionic

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
    - 7.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

install:
    - composer update

script:
    - vendor/phpunit/phpunit/phpunit --verbose
